# Open Asterisk
# Config.toml
[Dumpfolders]
folders = ["D:\\DATA_LEAKS\\TEST_SAMPLE\\COMBOLISTS","D:\\DATA_LEAKS\\TEST_SAMPLE\\DOCUMENTS"]

# Exporter Options
[[exporters]]
name = "CSVExporter"
location = "./modules/exporters/csv_exporter.py"
database = 'data.csv'
enabled = false

[[exporters]]
name = "SQLiteExporter"
location = "./modules/exporters/sqlite_exporter.py"
database = 'database.sql'
enabled = true

# Modules Options
[[modules]]
name = "CombolistExtractor"
location = "./modules/breach_data/combolist.py"
enabled = true

[[modules]]
name = "MicrosoftOfficeExtractor"
location = "./modules/metadata/microsoft_office_document.py"
enabled = true